create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
create table activity (id int4 generated by default as identity, activity_name varchar(255), category int4, primary key (id))
create table category (id int4 generated by default as identity, category_name varchar(255), primary key (id))
create table person (id int4 generated by default as identity, first_name varchar(255), last_name varchar(255), password varchar(255), role_id int4 not null, user_name varchar(255), primary key (id))
create table time_log (id int4 generated by default as identity, activity_id int4 not null, duration time, end_at time, start_at time, status int4 not null, user_id int4 not null, primary key (id))
alter table if exists activity add constraint FK4kk8j31baa6w4i2agnmn5oxsi foreign key (category) references category
